### PR TITLE
[#10672] improvement(auth): Return specific error message when authentication token is expired

### LINKED ISSUE #10672: [Improvement] Return authentication timeout error response when token is expired
### What would you like to be improved?

When a JWT token has expired, the server currently returns a generic error message ("JWT parse error" or "JWKS JWT validation error") rather than a specific authentication timeout message. This makes it impossible for clients to distinguish an expired token from a malformed token or invalid signature.

The issue affects two validators:

StaticSignKeyValidator — ExpiredJwtException is caught in the same multi-catch as MalformedJwtException, UnsupportedJwtException, SignatureException, etc., and returns the generic "JWT parse error".
JwksTokenValidator — All exceptions are caught generically and return "JWKS JWT validation error", regardless of whether the token was expired or had a different fault.
Clients receive a 401 Unauthorized with no way to determine whether they should refresh/re-authenticate vs. debug a misconfigured token.

### How should we improve?

In StaticSignKeyValidator, split ExpiredJwtException into its own catch block and return "Authentication token is expired".
In JwksTokenValidator, add a catch (BadJWTException e) block that inspects the message for expiry and returns "Authentication token is expired".
This gives clients an actionable error and improves observability.

### PR DESCRIPTION
**Pull request by laserninja**
### What changes were proposed in this pull request?

Split the `ExpiredJwtException` / `BadJWTException` catch blocks in `StaticSignKeyValidator` and `JwksTokenValidator` to return the specific message `"Authentication token is expired"` instead of the generic `"JWT parse error"` / `"JWKS JWT validation error"`.

Also adds regression tests (`testValidateExpiredTokenHasCorrectMessage`) in both test classes to guard against the message regressing.

### Why are the changes needed?

Clients receiving a `401 Unauthorized` had no way to distinguish an expired token from a malformed or wrongly-signed token. An actionable error message lets clients know they should refresh/re-authenticate rather than debug a configuration issue.

Fix: #10672

### Does this PR introduce _any_ user-facing change?

Yes — the `401 Unauthorized` error message for an expired JWT changes from `"JWT parse error"` (static key) or `"JWKS JWT validation error"` (JWKS) to `"Authentication token is expired"`.

### How was this patch tested?

- Added `testValidateExpiredTokenHasCorrectMessage` to `TestStaticSignKeyValidator` and `TestJwksTokenValidator`.
- All existing and new unit tests pass (`./gradlew :server-common:test`).

### CODE REVIEW

**Comment by roryqi** [comment]
We should return AuthenticationTimeoutResponse， you can see https://github.com/apache/iceberg/blob/9a939d68358de9dac2c6ba9b236b675ebe477490/open-api/rest-catalog-open-api.yaml#L292
I think we can continue this pull request after https://github.com/apache/gravitino/pull/10668

**Comment by roryqi** [comment]
> We should return AuthenticationTimeoutResponse， you can see https://github.com/apache/iceberg/blob/9a939d68358de9dac2c6ba9b236b675ebe477490/open-api/rest-catalog-open-api.yaml#L292 I think we can continue this pull request after #10668

@laserninja Maybe we can continue this pull request after merging #10668

File: server-common/src/main/java/org/apache/gravitino/server/authentication/JwksTokenValidator.java [hunk 1]
```diff
@@ -161,6 +163,12 @@ public Principal validateToken(String token, String serviceAudience) {
       }
       return userPrincipal;
 
+    } catch (BadJWTException e) {
```
Comment (roryqi) [inline server-common/src/main/java/org/apache/gravitino/server/authentication/JwksTokenValidator.java]: Could u use here?
```
package com.nimbusds.jwt.proc;

public class ExpiredJWTException extends BadJWTException {
    public ExpiredJWTException(String message) {
        super(message);
    }
}
```

File: iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/IcebergExceptionMapper.java [hunk 2]
```diff
@@ -97,6 +99,9 @@ public static int getErrorCode(Exception ex) {
    */
   public static Exception convertToIcebergException(Exception e) {
     String message = e.getMessage() != null ? e.getMessage() : "";
+    if (e instanceof TokenExpiredException) {
+      return e;
```
Comment (roryqi) [inline iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/IcebergExceptionMapper.java]: We should Iceberg Exception here instead of Gravitino Exception here.

Comment (laserninja) [reply iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/IcebergExceptionMapper.java]: Sounds good. I've created `AuthenticationTimeoutException extends RESTException' in the iceberg-rest-server module (the Iceberg SDK doesn't ship this class despite it being part of the REST spec). IcebergExceptionMapper.convertToIcebergException() now converts TokenExpiredException → 'AuthenticationTimeoutException', so only the Iceberg exception type reaches the HTTP response.

File: server-common/src/main/java/org/apache/gravitino/server/authentication/JwksTokenValidator.java (hunk 1 above)
Comment (laserninja) [reply server-common/src/main/java/org/apache/gravitino/server/authentication/JwksTokenValidator.java]: ExpiredJWTException does not exist in nimbus-jose-jwt 9.37.3 (the version Gravitino uses) as it was introduced in 10.x. Since upgrading nimbus is a larger change, I've kept the BadJWTException catch with message checking and added a comment explaining why. If/when Gravitino upgrades to nimbus 10.x, we can switch to catching ExpiredJWTException directly. Let me know if you want me to create another MR for that.

Comment (roryqi) [reply server-common/src/main/java/org/apache/gravitino/server/authentication/JwksTokenValidator.java]: Maybe we can raise an another pull request to upgrade nimbus. This seems a work around. We should avoid work around fix as possible as we can.

Comment (laserninja) [reply server-common/src/main/java/org/apache/gravitino/server/authentication/JwksTokenValidator.java]: Done https://github.com/apache/gravitino/pull/10773

**Review by roryqi — APPROVED** [review]
