### PR TITLE
[#10830] feat(api): add View, ViewCatalog, ViewChange and SQLRepresentation APIs

### LINKED ISSUE #10830: [Subtask] add table view APIs
### Describe the subtask

Add the public Java API surface for Gravitino logical view management, as specified in `design-docs/gravitino-logical-view-management.md`.

New types added in the `api/` module:

- `View`: view metadata with columns, SQL representations, security mode, and a helper to look up a representation by dialect.
- `ViewCatalog`: `listViews`, `createView`, `alterView`, `dropView` operations.
- `ViewChange`: supported view mutations (rename, update comment, set/remove property, update SQL definition).
- `SQLRepresentation` / `Representation`: multi-dialect view definition container.
- `Dialects`: predefined dialect constants (`hive`, `trino`, `spark`, `flink`).
- `SecurityMode`: `DEFINER` / `INVOKER` security mode enum.
- `ViewAlreadyExistsException`: exception for duplicate view creation.

### Parent issue

#604

### PR DESCRIPTION
**Pull request by mchades**
### What changes were proposed in this pull request?

This PR introduces the first batch of logical view support, focused on API surface plus the `loadView` read path.

Changes included:

1. API additions in `api/`:
   - `View`
   - `ViewCatalog`
   - `ViewChange`
   - `Representation` / `SQLRepresentation`
   - `Dialects`
   - `ViewAlreadyExistsException`
2. Core load path in `core/`:
   - `ViewOperationDispatcher` now supports `loadView(...)` with EntityStore auto-import.
   - `EntityCombinedView` to combine catalog-side view metadata and Gravitino entity metadata.
3. Catalog adapter/test support:
   - `IcebergView` implementation for mapping Iceberg REST `LoadViewResponse` to Gravitino `View`.
   - `TestCatalogOperations` and `TestViewOperationDispatcher` coverage for view loading and auto-import behavior.

Out of scope in this PR:
- Full view CRUD implementation in dispatcher/connectors (`listViews/createView/alterView/dropView`) is **not** implemented yet.

### Why are the changes needed?

This is the foundational step for logical view management in Gravitino, establishing the public API model and enabling the initial `loadView` integration path.

Fix: #10830

### Does this PR introduce _any_ user-facing change?

Yes.

- New public API types for view management are added in the `api` module.
- Runtime behavior change is limited to the `loadView` path introduced in core dispatcher flow.
- `createView/alterView/dropView/listViews` runtime support is not part of this PR.

### How was this change tested?

- Added/updated API unit tests:
  - `api/src/test/java/org/apache/gravitino/rel/TestSQLRepresentation.java`
  - `api/src/test/java/org/apache/gravitino/rel/TestView.java`
  - `api/src/test/java/org/apache/gravitino/rel/TestViewChange.java`
- Added core dispatcher tests:
  - `core/src/test/java/org/apache/gravitino/catalog/TestViewOperationDispatcher.java`
- Updated connector test utilities:
  - `core/src/test/java/org/apache/gravitino/connector/TestCatalogOperations.java`

### CODE REVIEW

File: api/src/main/java/org/apache/gravitino/rel/Dialects.java [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+  public static final String SPARK = "spark";
+
+  /** The Apache Hive SQL dialect. */
+  public static final String HIVE = "hive";
+
+  /** The Apache Flink SQL dialect. */
+  public static final String FLINK = "flink";
+
+  private Dialects() {}
+}
```
Comment (jerryshao) [inline api/src/main/java/org/apache/gravitino/rel/Dialects.java:43]: Shall we use enum?

File: api/src/main/java/org/apache/gravitino/rel/Representation.java [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+/**
+ * A representation of a view's underlying definition. A view can carry multiple representations
+ * targeting different engines or dialects. Currently only the {@link #TYPE_SQL SQL} representation
+ * type is supported.
+ */
+@Unstable
+public interface Representation {
+
+  /** The representation type for SQL-based view definitions. */
+  String TYPE_SQL = "sql";
```
Comment (jerryshao) [inline api/src/main/java/org/apache/gravitino/rel/Representation.java:32]: Also for this.

File: api/src/main/java/org/apache/gravitino/rel/Dialects.java (hunk 1 above)
Comment (mchades) [reply api/src/main/java/org/apache/gravitino/rel/Dialects.java:43]: I suggest keeping `dialect` as string (with constants), not enum.

This aligns with both our design and Iceberg:
- Gravitino design doc defines dialect as a free-form string (not a fixed enum): https://github.com/mchades/gravitino/blob/defacfbe6/design-docs/gravitino-logical-view-management.md#L119-L121
- Iceberg models dialect as `String` in `SQLViewRepresentation#dialect()`: https://github.com/apache/iceberg/blob/apache-iceberg-1.10.1/api/src/main/java/org/apache/iceberg/view/SQLViewRepresentation.java#L22-L33

So `Dialects` is intended to provide well-known constants for typo reduction, not a closed set.

File: api/src/main/java/org/apache/gravitino/rel/Representation.java (hunk 2 above)
Comment (mchades) [reply api/src/main/java/org/apache/gravitino/rel/Representation.java:32]: For `Representation#type`, I prefer keeping `String` in the public API.

Although only `sql` is built-in today, `type` is designed for forward extensibility:
- design doc (`type` is extensible): https://github.com/mchades/gravitino/blob/defacfbe6/design-docs/gravitino-logical-view-management.md#L115-L117
- Iceberg `ViewRepresentation#type()` is also `String`: https://github.com/apache/iceberg/blob/apache-iceberg-1.10.1/api/src/main/java/org/apache/iceberg/view/ViewRepresentation.java#L21-L29
- Iceberg also keeps `UnknownViewRepresentation`: https://github.com/apache/iceberg/blob/apache-iceberg-1.10.1/core/src/main/java/org/apache/iceberg/view/UnknownViewRepresentation.java#L23-L24

So `TYPE_SQL` remains a stable built-in constant, while the API stays extensible.

File: catalogs/catalog-lakehouse-iceberg/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergView.java [hunk 3]
```diff
@@ -68,6 +70,16 @@ public Map<String, String> properties() {
...
 
+  @Override
+  public Column[] columns() {
+    return new Column[0];
+  }
+
+  @Override
+  public Representation[] representations() {
+    return new Representation[0];
+  }
```
[the remark this answers is not in the document]
Comment (mchades) [reply catalogs/catalog-lakehouse-iceberg/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergView.java:81]: Agreed this is a functional gap for the Iceberg load path.

For this PR, I’m keeping scope on API surface and core dispatcher correctness. I will address Iceberg view metadata mapping (including `representations` from `LoadViewResponse`) in a dedicated follow-up PR.

File: api/src/main/java/org/apache/gravitino/rel/ViewCatalog.java [hunk 4]
```diff
@@ -54,4 +65,54 @@ default boolean viewExists(NameIdentifier ident) {
...
+   */
+  View createView(
+      NameIdentifier ident,
+      String comment,
+      Column[] columns,
+      Representation[] representations,
+      @Nullable String defaultCatalog,
+      @Nullable String defaultSchema,
+      Map<String, String> properties)
+      throws NoSuchSchemaException, ViewAlreadyExistsException;
```
[the remark this answers is not in the document]
Comment (mchades) [reply api/src/main/java/org/apache/gravitino/rel/ViewCatalog.java]: Fixed in commit `defacfbe6`: `createView(...)` now annotates `comment` with `@Nullable` to match the JavaDoc.

File: catalogs/catalog-lakehouse-iceberg/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergView.java [hunk 5]
```diff
@@ -68,6 +70,16 @@ public Map<String, String> properties() {
     return properties != null ? properties : Collections.emptyMap();
   }
 
+  @Override
+  public Column[] columns() {
+    return new Column[0];
+  }
```
[the remark this answers is not in the document]
Comment (mchades) [reply catalogs/catalog-lakehouse-iceberg/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergView.java:76]: Agreed. `columns()` should be populated from Iceberg view metadata when available.

I will cover this together with `representations` mapping in the dedicated Iceberg follow-up PR, so this PR remains focused on API definition and core dispatcher fixes.

**Comment by jerryshao** [comment]
We'd move the core changes to another PR.

**Comment by mchades** [comment]
removed unnecessary changes in core

File: api/src/main/java/org/apache/gravitino/rel/ViewChange.java [hunk 6]
```diff
@@ -0,0 +1,338 @@
...
+    public String toString() {
+      return "REMOVEPROPERTY " + property;
+    }
+  }
+
+  /**
+   * A ViewChange that atomically replaces the view body (columns, representations, default catalog,
+   * default schema and comment).
+   */
+  final class ReplaceView implements ViewChange {
```
Comment (jerryshao) [inline api/src/main/java/org/apache/gravitino/rel/ViewChange.java:232]: How do we support this from query engine level?

Comment (mchades) [reply api/src/main/java/org/apache/gravitino/rel/ViewChange.java:232]: Replace view is a common syntax, such as https://spark.apache.org/docs/latest/sql-ref-syntax-ddl-create-view.html

File: api/src/main/java/org/apache/gravitino/rel/View.java [hunk 7]
```diff
@@ -20,33 +20,108 @@
...
 import org.apache.gravitino.Namespace;
 import org.apache.gravitino.annotation.Unstable;
 
 /**
- * An interface representing a view in a {@link Namespace}. It defines the basic properties of a
- * view. A catalog implementation with {@link ViewCatalog} should implement this interface.
+ * An interface representing a logical view in a {@link Namespace}. A view is a named query whose
+ * definition may be expressed in one or more SQL dialects. A catalog implementation with {@link
+ * ViewCatalog} should implement this interface.
  */
```
[the remark this answers is not in the document]
Comment (mchades) [reply api/src/main/java/org/apache/gravitino/rel/View.java:33]: updated

File: api/src/main/java/org/apache/gravitino/rel/View.java [hunk 8]
```diff
@@ -20,33 +20,108 @@
...
+   * @return The view output columns.
+   */
+  Column[] columns();
+
+  /**
+   * Returns the representations of the view. A view carries at least one {@link Representation},
+   * typically a {@link SQLRepresentation} for one or more dialects.
+   *
+   * @return The view representations.
+   */
```
[the remark this answers is not in the document]
Comment (mchades) [reply api/src/main/java/org/apache/gravitino/rel/View.java:67]: dropped the null branch in sqlFor

**Review by jerryshao — APPROVED** [review]
