### PR TITLE
[#7346] fix(catalogs): modify the error message in model catalog

### LINKED ISSUE #7346: [Bug report] Incorrect error message ModelVersionAliasesAlreadyExistException
### Version

main branch

### Describe what's wrong

"test.cat.s1.model3" is the model name , not the duplicated aliases
```
  "org.apache.gravitino.exceptions.ModelVersionAliasesAlreadyExistException: Model version aliases test.cat.s1.model3 already exist",
  "\tat org.apache.gravitino.catalog.model.ModelCatalogOperations.linkModelVersion(ModelCatalogOperations.java:242)",
  "\tat org.apache.gravitino.catalog.ModelOperationDispatcher.lambda$linkModelVersion$23(ModelOperationDispatcher.java:185)",
  "\tat org.apache.gravitino.catalog.CatalogManager$CatalogWrapper.lambda$doWithModelOps$5(CatalogManager.java:195)",

```

### Error message and/or stacktrace

N/A

### How to reproduce

Link  2 version under the same model with duplicated aliases.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by KyleLin0927**
### What changes were proposed in this pull request?

updates the error message in `catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelCatalogOperations.java` to correctly display.

### Why are the changes needed?

Fixes #7346

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

- Ran `./gradlew clean build`.

### CODE REVIEW

File: catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelCatalogOperations.java [hunk 1]
```diff
@@ -242,8 +242,7 @@ public void linkModelVersion(
     } catch (IOException e) {
       throw new RuntimeException("Failed to link model version " + ident, e);
     } catch (EntityAlreadyExistsException e) {
-      throw new ModelVersionAliasesAlreadyExistException(
-          e, "Model version aliases %s already exist", ident);
+      throw new ModelVersionAliasesAlreadyExistException(e, "Model version alias already exists");
```
Comment (yuqi1129) [inline catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelCatalogOperations.java]: I think you may need to record both the model and its alias at the same time.

Comment (KyleLin0927) [reply catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelCatalogOperations.java]: thanks for suggest. I initially used `modelVersion.aliases()` to show all aliases in the error message, but it listed all added aliases, not just the duplicate one.

I suggest simplifying the message to: `Model version alias already exists in model %s`. This keeps message clear without giving misleading details.

Comment (yuqi1129) [reply catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelCatalogOperations.java]: It's also LGTM.

Comment (KyleLin0927) [reply catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelCatalogOperations.java]: done

**Review by yuqi1129 — APPROVED** [review]
