### PR TITLE
[#7218] improvement(spark-connector): Add null check for partition column names

### LINKED ISSUE #7218: [Improvement] Possible NullPointerException  when invoking method getHivePartitionName()
### What would you like to be improved?

In spark-connector/spark-common/src/main/java/org/apache/gravitino/spark/connector/utils/HiveGravitinoOperationOperator.java in listPartitionIdentifiers a null pointer exception could occure when callling  getHivePartitionName as getHivePartitionName uses names.length.

### How should we improve?

Add a null check or similar.

### PR DESCRIPTION
**Pull request by KyleLin0927**
### What changes were proposed in this pull request?

Added a null check for the names parameter in `getHivePartitionName` to avoid potential NPE.

### Why are the changes needed?

Fixes #7218

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

- Ran `./gradlew clean build`

### CODE REVIEW

File: spark-connector/spark-common/src/main/java/org/apache/gravitino/spark/connector/utils/HiveGravitinoOperationOperator.java [hunk 1]
```diff
@@ -145,6 +145,9 @@ private InternalRow toSparkPartition(String partitionName, StructType partitionS
   private @NotNull String getHivePartitionName(
       String[] names, InternalRow ident, StructType partitionSchema) {
     StringBuilder partitionName = new StringBuilder();
+    if (names == null) {
```
Comment (FANNG1) [inline spark-connector/spark-common/src/main/java/org/apache/gravitino/spark/connector/utils/HiveGravitinoOperationOperator.java:148]: Could you use `Preconditions.checkArgument` instead?

**Review by FANNG1 — APPROVED** [review]
