### PR TITLE
[#10381][#10378] fix(clickhouse-catalog):  Fix ClickHouse alter-table bugs

### LINKED ISSUE #10378: [Bug report] Failed to add table index/delete table index
### Version

main branch

### Describe what's wrong

Failed to add table index and delete table index.

Image

Image

### Error message and/or stacktrace

```
{
    "code": 1001,
    "type": "IllegalArgumentException",
    "message": "Failed to operate table(s) [orders] operation [ALTER] under schema [sales], reason [Unsupported table change type: org.apache.gravitino.rel.TableChange$AddIndex]",
    "stack": [
        "java.lang.IllegalArgumentException: Unsupported table change type: org.apache.gravitino.rel.TableChange$AddIndex",
        "\tat org.apache.gravitino.catalog.clickhouse.operations.ClickHouseTableOperations.generateAlterTableSql(ClickHouseTableOperations.java:733)",
        "\tat org.apache.gravitino.catalog.clickhouse.operations.ClickHouseTableOperations.alterTable(ClickHouseTableOperations.java:509)",
        "\tat org.apache.gravitino.catalog.jdbc.JdbcCatalogOperations.internalAlterTable(JdbcCatalogOperations.java:589)",
        "\tat org.apache.gravitino.catalog.jdbc.JdbcCatalogOperations.alterTable(JdbcCatalogOperations.java:439)",
        "\tat org.apache.gravitino.catalog.TableOperationDispatcher.lambda$alterTable$6(TableOperationDispatcher.java:235)",
        "\tat org.apache.gravitino.catalog.CatalogManager$CatalogWrapper.lambda$doWithTableOps$1(CatalogManager.java:153)",
        "\tat org.apache.gravitino.utils.IsolatedClassLoader.withClassLoader(IsolatedClassLoader.java:86)",
        "\tat org.apache.gravitino.catalog.CatalogManager$CatalogWrapper.doWithTableOps(CatalogManager.java:148)",
        "\tat org.apache.gravitino.catalog.TableOperationDispatcher.lambda$alterTable$7(TableOperationDispatcher.java:234)",
        "\tat org.apache.gravitino.catalog.OperationDispatcher.doWithCatalog(OperationDispatcher.java:117)",
        "\tat org.apache.gravitino.catalog.TableOperationDispatcher.lambda$alterTable$10(TableOperationDispatcher.java:231)",
        "\tat org.apache.gravitino.lock.TreeLockUtils.doWithTreeLock(TreeLockUtils.java:49)",
        "\tat org.apache.gravitino.catalog.TableOperationDispatcher.alterTable(TableOperationDispatcher.java:225)",
        "\tat org.apache.gravitino.hook.TableHookDispatcher.alterTable(TableHookDispatcher.java:106)",
        "\tat org.apache.gravitino.catalog.TableNormalizeDispatcher.alterTable(TableNormalizeDispatcher.java:93)",
        "\tat org.apache.gravitino.listener.TableEventDispatcher.alterTable(TableEventDispatcher.java:155)",
        "\tat org.apache.gravitino.server.web.rest.TableOperations.lambda$alterTable$4(TableOperations.java:234)",
        "\tat java.base/java.security.AccessController.doPrivileged(AccessController.java:712)",
        "\tat java.base/javax.security.auth.Subject.doAs(Subject.java:439)",
        "\tat org.apache.gravitino.utils.PrincipalUtils.doAs(PrincipalUtils.java:44)",
        "\tat org.apache.gravitino.server.web.Utils.doAs(Utils.java:202)",
        "\tat org.apache.gravitino.server.web.rest.TableOperations.alterTable(TableOperations.java:225)",
        "\tat org.apache.gravitino.server.web.rest.TableOperations_$$_jvst993_9._d1alterTable(TableOperations_$$_jvst993_9.java)",
        "\tat jdk.internal.reflect.GeneratedMethodAccessor86.invoke(Unknown Source)",
        "\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
        "\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)",
        "\tat org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1268)",
        "\tat org.jvnet.hk2.internal.MethodInterceptorHandler$MethodInvocationImpl.proceed(MethodInterceptorHandler.java:164)",
        "\tat org.apache.gravitino.server.web.filter.GravitinoInterceptionService$MetadataAuthorizationMethodInterceptor.invoke(GravitinoInterceptionService.java:208)",
        "\tat org.jvnet.hk2.internal.MethodInterceptorHandler.invoke(MethodInterceptorHandler.java:97)",
        "\tat org.apache.gravitino.server.web.rest.TableOperations_$$_jvst993_9.alterTable(TableOperations_$$_jvst993_9.java)",
        "\tat jdk.internal.reflect.GeneratedMethodAccessor85.invoke(Unknown Source)",
        "\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
        "\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)",
        "\tat org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)",
        "\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146)",
        "\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189)",
        "\tat org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)",
        "\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93)",
        "\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)",
        "\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)",
        "\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)",
        "\tat org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:256)",
        "\tat org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)",
        "\tat org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)",
        "\tat org.glassfish.jersey.internal.Errors.process(Errors.java:292)",
        "\tat org.glassfish.jersey.internal.Errors.process(Errors.java:274)",
        "\tat org.glassfish.jersey.internal.Errors.process(Errors.java:244)",
        "\tat org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)",
        "\tat org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235)",
        "\tat org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)",
        "\tat org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)",
        "\tat org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)",
        "\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358)",
        "\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)",
        "\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)",
        "\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)",
        "\tat org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656)",
        "\tat org.apache.gravitino.server.authentication.AuthenticationFilter.lambda$doFilter$0(AuthenticationFilter.java:89)",
        "\tat java.base/java.security.AccessController.doPrivileged(AccessController.java:712)",
        "\tat java.base/javax.security.auth.Subject.doAs(Subject.java:439)",
        "\tat org.apache.gravitino.utils.PrincipalUtils.doAs(PrincipalUtils.java:44)",
        "\tat org.apache.gravitino.server.authentication.AuthenticationFilter.doFilter(AuthenticationFilter.java:86)",
        "\tat org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)",
        "\tat org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)",
        "\tat org.apache.gravitino.server.web.VersioningFilter.doFilter(VersioningFilter.java:111)",
        "\tat org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)",
        "\tat org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)",
        "\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)",
        "\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)",
        "\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600)",
        "\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)",
        "\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)",
        "\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)",
        "\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)",
        "\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)",
        "\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)",
        "\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)",
        "\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)",
        "\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)",
        "\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)",
        "\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)",
        "\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)",
        "\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)",
        "\tat org.eclipse.jetty.server.Server.handle(Server.java:516)",
        "\tat org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)",
        "\tat org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)",
        "\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)",
        "\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)",
        "\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)",
        "\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)",
        "\tat org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)",
        "\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)",
        "\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)",
        "\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)",
        "\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)",
        "\tat org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)",
        "\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)",
        "\tat org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)",
        "\tat java.base/java.lang.Thread.run(Thread.java:840)"
    ]
}
```

### How to reproduce

1. Create ClickHouse/Hive catalog in gravitino
2. Create ClickHouse/Hive schema, table
3. Add primary index for the table
```
Request method:	PUT
Request URI:	http://127.0.0.1:8090/api/metalakes/clickhouse_test/catalogs/ck_catalog1/schemas/sales/tables/orders
Proxy:			<none>
Request params:	<none>
Query params:	<none>
Form params:	<none>
Path params:	<none>
Headers:		Accept=application/vnd.gravitino.v1+json
				Authorization=Basic YW5vbnltb3VzOnRlc3Q=
				Content-Type=application/json
Cookies:		<none>
Multiparts:		<none>
Body:
{
    "updates": [
        {
            "@type": "addTableIndex",
            "index": {
                "indexType": "PRIMARY_KEY",
                "name": "idx_customer",
                "fieldNames": [
                    [
                        "customer_id"
                    ]
                ]
            }
        }
    ]
}
```
4. Delete index for the table
```
Request method:	PUT
Request URI:	http://127.0.0.1:8090/api/metalakes/clickhouse_test/catalogs/ck_catalog1/schemas/sales/tables/orders
{
    "updates": [
        {
            "@type": "deleteTableIndex",
            "name": "a",
            "ifExists": true
        }
    ]
}
```
### Additional context

_No response_

### LINKED ISSUE #10381: [Bug report] Create a ClickHouse table with "autoIncrement": true didn't throw 400 or 405 exception
### Version

main branch

### Describe what's wrong

In our doc, we didn't support create a clickhouse table with Auto-increment columns through gravitino API.
But I can create a table with "autoIncrement": true  in column, it response Status code: 200

It's expected to throw unsupported message, response 400/405

Image

Image

### Error message and/or stacktrace

N/A

### How to reproduce

Create a Click House table:
```
URL: http://127.0.0.1:18090/api/metalakes/clickhouse_test/catalogs/ck_catalog1/schemas/ck_db/tables

Status code: 200

Content Type: application/json

Request Headers
Accept=application/vnd.gravitino.v1+json
Authorization=Basic YW5vbnltb3VzOnRlc3Q=
Content-Type=application/json
Content Body
{
    "name": "auto_inc_table2",
    "comment": "Invalid table with auto-increment column",
    "columns": [
        {
            "name": "id",
            "type": "integer",
            "comment": "ID",
            "nullable": false,
            "autoIncrement": true
        },
        {
            "name": "data",
            "type": "string",
            "comment": "Data",
            "nullable": false
        }
    ],
    "properties": {
        "engine": "MergeTree"
    },
    "sortOrders": [
        {
            "sortTerm": {
                "type": "field",
                "fieldName": [
                    "id"
                ]
            },
            "direction": "asc",
            "nullOrdering": "nulls_first"
        }
    ]
}
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yuqi1129**
### What changes were proposed in this pull request?

Add comprehensive integration coverage for ClickHouse alter-table behavior in:
- `CatalogClickHouseIT`
- `CatalogClickHouseClusterIT`

The new tests exercise `ClickHouseTableOperations#generateAlterTableSql` branches in real ClickHouse environments, including:
- supported alter branches: add/update type/update default/update comment/update position/update nullability/delete index/delete column
- edge/no-op branches: delete missing column/index with `ifExists=true`
- unsupported branches: set/remove property, update auto increment, nested column add

Tests also verify resulting table metadata (column type/comment/nullability/index removal) after alter operations.

### Why are the changes needed?

To prevent regressions in ClickHouse ALTER TABLE SQL generation and close branch-level test gaps for issues discussed in #10381 and #10378.

Fixed: #10381
Fixed: #10372 
Fixed: #10396
Fixed: #10405

### Does this PR introduce _any_ user-facing change?

N/A

Closes #10381
Closes #10378

### CODE REVIEW

**Comment by yuqi1129** [comment]
Verified against real ClickHouse integration tests: ADD INDEX and DROP INDEX for data skipping indexes are supported and now implemented in generateAlterTableSql for DATA_SKIPPING_MINMAX and DATA_SKIPPING_BLOOM_FILTER. ADD INDEX PRIMARY_KEY via ALTER is not supported and stays explicit unsupported behavior. updateColumnAutoIncrement true/false is unsupported in tested ClickHouse 24.8 and tests now assert this behavior. Also updated unit and integration coverage to match runtime behavior.

File: catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseTableOperations.java [hunk 1]
```diff
@@ -427,6 +431,19 @@ private String toPartitionExpression(Transform transform) {
...
 
+  private void validateNoAutoIncrementColumns(JdbcColumn[] columns) {
+    if (ArrayUtils.isEmpty(columns)) {
+      return;
+    }
+
+    for (JdbcColumn column : columns) {
+      if (column.autoIncrement()) {
+        throw new UnsupportedOperationException(
+            "ClickHouse does not support auto increment column in CREATE TABLE");
```
Comment (diqiu50) [inline catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseTableOperations.java]: You'd better add the column name in the exception

File: catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseTableOperations.java [hunk 2]
```diff
@@ -768,6 +789,37 @@ protected String generateAlterTableSql(
     return result;
   }
 
+  @VisibleForTesting
```
Comment (diqiu50) [inline catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseTableOperations.java]: This annotation doesn’t have any effect, right?

File: docs/jdbc-clickhouse-catalog.md [hunk 3]
```diff
@@ -156,15 +156,15 @@ See [Manage Relational Metadata Using Gravitino](./manage-relational-metadata-us
...
+|---------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
+| Mapping             | Gravitino table maps to a ClickHouse table                                                                                                                                                                                                                                                 |
+| Engines             | Local engines: MergeTree family (`MergeTree` default, `ReplacingMergeTree`, `SummingMergeTree`, `AggregatingMergeTree`, `CollapsingMergeTree`, `VersionedCollapsingMergeTree`, `GraphiteMergeTree`), Distributed engine supports cluster mode with remote database/table and sharding key. |
```
Comment (diqiu50) [inline docs/jdbc-clickhouse-catalog.md]: Why do we remove these engins

Comment (yuqi1129) [reply docs/jdbc-clickhouse-catalog.md]: Gravitino will fail if we create ClickHouse tables with an engine like memory, as it will disappear when ClickHouse restarts.

File: catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseTableOperations.java (hunk 2 above)
Comment (yuqi1129) [reply catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseTableOperations.java]: Yeah, I have removed it.

File: catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseTableOperations.java (hunk 1 above)
Comment (yuqi1129) [reply catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseTableOperations.java]: OK

File: docs/jdbc-clickhouse-catalog.md [hunk 4]
```diff
@@ -156,15 +156,15 @@ See [Manage Relational Metadata Using Gravitino](./manage-relational-metadata-us
...
+| Distribution        | Gravitino enforces `Distributions.NONE`; no custom distribution strategies.                                                                                                                                                                                                                |
+| Column defaults     | Supported.                                                                                                                                                                                                                                                                                 |
+| Unsupported         | Engine change after creation; removing table properties; auto-increment columns.                                                                                                                                                                                                           |
```
[the remark this answers is not in the document]
Comment (yuqi1129) [reply docs/jdbc-clickhouse-catalog.md]: The table format is correct, please refer to the latest change.

File: catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseTableOperations.java [hunk 5]
```diff
@@ -768,6 +827,36 @@ protected String generateAlterTableSql(
...
+        ArrayUtils.isNotEmpty(addIndex.getFieldNames()), "Index field names are required");
+
+    boolean indexExists =
+        Arrays.stream(table.index()).anyMatch(index -> index.name().equals(addIndex.getName()));
+    Preconditions.checkArgument(!indexExists, "Index '%s' already exists", addIndex.getName());
+
+    String fieldStr = getIndexFieldStr(addIndex.getFieldNames());
+    switch (addIndex.getType()) {
+      case DATA_SKIPPING_MINMAX:
+        return "ADD INDEX %s %s TYPE minmax GRANULARITY 1"
```
Comment (yuqi1129) [inline catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseTableOperations.java:857]: Constant `1` and `3` in L847 will be tracked by https://github.com/apache/gravitino/issues/10446

**Comment by yuqi1129** [comment]
@diqiu50 
Could you help review it again?

File: docs/jdbc-clickhouse-catalog.md (hunk 3 above)
Comment (diqiu50) [reply docs/jdbc-clickhouse-catalog.md]: You can describe the supported engines in the docs.

File: catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseDatabaseOperations.java [hunk 6]
```diff
@@ -124,12 +127,65 @@ public void create(String databaseName, String comment, Map<String, String> prop
...
+  private String getDatabaseClusterName(Connection connection, String databaseName)
+      throws SQLException {
+    try (Statement stmt = connection.createStatement();
+        ResultSet rs =
+            stmt.executeQuery(String.format("SHOW CREATE DATABASE `%s`", databaseName))) {
+      if (rs.next()) {
+        String createSql = rs.getString(1);
+        Matcher matcher = ON_CLUSTER_PATTERN.matcher(createSql);
+        if (matcher.find()) {
+          return matcher.group(1);
```
Comment (diqiu50) [inline catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseDatabaseOperations.java]: I remember that the return value of `HOW CREATE DATABASE` does not contain the cluster name.

File: catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseDatabaseOperations.java [hunk 7]
```diff
@@ -124,12 +127,65 @@ public void create(String databaseName, String comment, Map<String, String> prop
   protected void dropDatabase(String databaseName, boolean cascade) {
     try (final Connection connection = getConnection()) {
       connection.setCatalog(createSysDatabaseNameSet().iterator().next());
-      JdbcConnectorUtils.executeUpdate(connection, generateDropDatabaseSql(databaseName, cascade));
+      if (!cascade) {
+        try (Statement stmt = connection.createStatement();
+            ResultSet rs = stmt.executeQuery(String.format("SHOW TABLES IN `%s`", databaseName))) {
```
Comment (diqiu50) [inline catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseDatabaseOperations.java]: You'd better use the system table to check table exists in db

File: catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseDatabaseOperations.java [hunk 8]
```diff
@@ -124,12 +127,65 @@ public void create(String databaseName, String comment, Map<String, String> prop
...
+   * @param databaseName The name of the database to drop.
+   * @param clusterName The cluster name extracted from the database's CREATE SQL, or {@code null}
+   *     if the database is not on a cluster.
+   * @return The DROP DATABASE SQL statement.
+   */
+  @VisibleForTesting
+  String generateDropDatabaseSql(String databaseName, String clusterName) {
+    StringBuilder sql = new StringBuilder(String.format("DROP DATABASE `%s`", databaseName));
+    if (StringUtils.isNotBlank(clusterName)) {
+      sql.append(String.format(" ON CLUSTER `%s` SYNC", clusterName));
```
Comment (diqiu50) [inline catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseDatabaseOperations.java]: We are not using sync, so the drop operation may time out.

File: catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseDatabaseOperations.java [hunk 9]
```diff
@@ -124,12 +127,65 @@ public void create(String databaseName, String comment, Map<String, String> prop
...
     try (final Connection connection = getConnection()) {
       connection.setCatalog(createSysDatabaseNameSet().iterator().next());
-      JdbcConnectorUtils.executeUpdate(connection, generateDropDatabaseSql(databaseName, cascade));
+      if (!cascade) {
+        try (Statement stmt = connection.createStatement();
+            ResultSet rs = stmt.executeQuery(String.format("SHOW TABLES IN `%s`", databaseName))) {
+          if (rs.next()) {
+            throw new IllegalStateException(
+                String.format(
+                    "Database %s is not empty, the value of cascade should be true.",
```
Comment (diqiu50) [inline catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseDatabaseOperations.java]: The message "Database mydb is not empty. You can drop it with CASCADE." is better,  a NoOpException should be returned.

File: docs/jdbc-clickhouse-catalog.md (hunk 3 above)
Comment (yuqi1129) [reply docs/jdbc-clickhouse-catalog.md]: updated @diqiu50

File: catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseDatabaseOperations.java (hunk 8 above)
Comment (yuqi1129) [reply catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseDatabaseOperations.java]: I'm struggling with it. If we drop it without `sync.`, we can still load the database even though we have dropped it.

File: catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseDatabaseOperations.java (hunk 7 above)
Comment (yuqi1129) [reply catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseDatabaseOperations.java]: What's the side effect of using `SHOW TABLES IN`?

File: catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseDatabaseOperations.java (hunk 6 above)
Comment (yuqi1129) [reply catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseDatabaseOperations.java]: fixed

File: catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseDatabaseOperations.java [hunk 10]
```diff
@@ -94,10 +104,12 @@ protected String generateCreateDatabaseSql(
...
-
-    if (StringUtils.isNotEmpty(originComment)) {
-      createDatabaseSql.append(String.format(" COMMENT '%s'", originComment));
+      // Embed the cluster name into the COMMENT so it can be retrieved later (e.g., at DROP time).
+      // ClickHouse does not persist ON CLUSTER info in SHOW CREATE DATABASE for Atomic databases.
+      String storedComment = embedClusterInComment(originComment, clusterName);
+      createDatabaseSql.append(String.format(" COMMENT '%s'", storedComment.replace("'", "''")));
+    } else if (StringUtils.isNotEmpty(originComment)) {
+      createDatabaseSql.append(String.format(" COMMENT '%s'", originComment.replace("'", "''")));
     }
```
Comment (diqiu50) [inline catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseDatabaseOperations.java:114]: Add the functions escapeComments and unescapeComments to handle here

File: catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseDatabaseOperations.java (hunk 7 above)
Comment (diqiu50) [reply catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseDatabaseOperations.java]: May be the table is just not in this host, if you don't want handle this case, add some comments

File: catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseDatabaseOperations.java [hunk 11]
```diff
@@ -133,12 +180,14 @@ protected void dropDatabase(String databaseName, boolean cascade) {
           if (rs.next()) {
             throw new IllegalStateException(
                 String.format(
```
Comment (diqiu50) [inline catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseDatabaseOperations.java]: Should NoOpException

File: catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseDatabaseOperations.java (hunk 8 above)
Comment (diqiu50) [reply catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseDatabaseOperations.java]: In a normal ClickHouse cluster, the database should not be visible after being dropped.

File: catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseTableOperations.java [hunk 12]
```diff
@@ -798,14 +804,19 @@ protected String generateAlterTableSql(
...
+        lazyLoadTable = getOrCreateTable(databaseName, tableName, lazyLoadTable);
+        StringIdentifier identifier = StringIdentifier.fromComment(lazyLoadTable.comment());
         if (null != identifier) {
           newComment = StringIdentifier.addToComment(identifier, newComment);
         }
       }
-      String escapedComment = newComment.replace("'", "''");
-      alterSql.add(" MODIFY COMMENT '%s'".formatted(escapedComment));
+      // Re-embed cluster metadata so it is not lost when the comment is updated.
+      lazyLoadTable = getOrCreateTable(databaseName, tableName, lazyLoadTable);
```
Comment (diqiu50) [inline catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseTableOperations.java]: Why we call the getOrCreateTable twice

File: catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseTableOperations.java [hunk 13]
```diff
@@ -798,14 +804,19 @@ protected String generateAlterTableSql(
...
+      String clusterName = lazyLoadTable.properties().get(ClusterConstants.CLUSTER_NAME);
+      if (StringUtils.isNotBlank(clusterName)) {
+        newComment = ClickHouseClusterUtils.embedClusterInComment(newComment, clusterName);
+      }
+      alterSql.add(" MODIFY COMMENT '%s'".formatted(newComment.replace("'", "''")));
```
Comment (diqiu50) [inline catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseTableOperations.java]: Call the unEscapeComment function is better

File: catalogs-contrib/catalog-jdbc-clickhouse/src/test/java/org/apache/gravitino/catalog/clickhouse/operations/TestClickHouseTableOperationsCluster.java [hunk 14]
```diff
@@ -254,6 +259,107 @@ void testGenerateDropTableSqlOnClusterWithoutClusterName() {
...
+  // ---------------------------------------------------------------------------
+  // Cluster metadata embedded in COMMENT
+  // ---------------------------------------------------------------------------
+
+  /**
+   * When a MergeTree table is created ON CLUSTER, the cluster name must be embedded in the stored
+   * COMMENT so it can be recovered at DROP/load time (SHOW CREATE TABLE omits ON CLUSTER).
+   */
+  @Test
+  void testCreateTableOnClusterEmbedsCluterNameInComment() {
```
Comment (diqiu50) [inline catalogs-contrib/catalog-jdbc-clickhouse/src/test/java/org/apache/gravitino/catalog/clickhouse/operations/TestClickHouseTableOperationsCluster.java]: Cluster

File: catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseClusterUtils.java [hunk 15]
```diff
@@ -0,0 +1,111 @@
...
+ * because Gravitino strips it before surfacing the comment.
+ *
+ * <p><b>Stored format:</b> {@code userComment\u0001ch.cluster=clusterName}
+ *
+ * <p><b>Limitation:</b> This mechanism only works for databases and tables created through
+ * Gravitino. If a database or table was created directly in ClickHouse (bypassing Gravitino),
+ * Gravitino has no way to determine whether it was created {@code ON CLUSTER} or which cluster name
+ * was used. In that case {@link #extractClusterFromComment} returns {@code null} and the {@code
+ * on-cluster} / {@code cluster-name} properties reported by Gravitino will be absent or inaccurate.
+ */
```
Comment (diqiu50) [inline catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseClusterUtils.java:99]: Give an example for the comment of `show create table` command

File: catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseClusterUtils.java [hunk 16]
```diff
@@ -0,0 +1,111 @@
...
+public final class ClickHouseClusterUtils {
+
+  /**
+   * Separator character between the user comment and the cluster metadata token. SOH (U+0001) is a
+   * non-printable control character that will not appear in normal user-supplied comments.
+   */
+  @VisibleForTesting public static final char CLUSTER_META_SEP = '\u0001';
```
Comment (diqiu50) [inline catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseClusterUtils.java]: The separator is invisible to users, so it cannot be manually fixed when have some bugs.

File: catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseTableOperations.java [hunk 17]
```diff
@@ -190,10 +188,15 @@ protected String generateCreateTableSql(
...
-      sqlBuilder.append(" COMMENT '%s'".formatted(escapedComment));
+    // Add table comment; embed cluster name so it can be recovered at DROP/ALTER time.
+    // ClickHouse does not persist ON CLUSTER in SHOW CREATE TABLE (see ClickHouseClusterUtils).
+    String storedComment =
+        onCluster
+            ? ClickHouseClusterUtils.embedClusterInComment(
+                comment, notNullProperties.get(ClusterConstants.CLUSTER_NAME))
+            : comment;
+    if (StringUtils.isNotEmpty(storedComment)) {
+      sqlBuilder.append(" COMMENT '%s'".formatted(storedComment.replace("'", "''")));
```
Comment (diqiu50) [inline catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseTableOperations.java]: The same problem

File: catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseClusterUtils.java (hunk 16 above)
Comment (diqiu50) [reply catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseClusterUtils.java]: Add a hit to mark it's generate by Gravitino server

Comment (yuqi1129) [reply catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseClusterUtils.java]: done

File: catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseTableOperations.java (hunk 12 above)
Comment (yuqi1129) [reply catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseTableOperations.java]: Add comment

File: catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseDatabaseOperations.java (hunk 11 above)
Comment (yuqi1129) [reply catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseDatabaseOperations.java]: I use  the `IllegalArgumentException` to replace it.

File: catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseDatabaseOperations.java (hunk 8 above)
Comment (yuqi1129) [reply catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseDatabaseOperations.java]: remove SYNC

File: catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseClusterUtils.java [hunk 18]
```diff
@@ -36,11 +36,60 @@
...
+ * <p><b>Example — table created ON CLUSTER:</b>
+ *
+ * <pre>
+ * -- Gravitino issues:
+ * CREATE TABLE `orders` ON CLUSTER `ck_cluster`
+ *   (`id` Int32, `amount` Decimal(10,2))
+ *   ENGINE = MergeTree()
+ *   ORDER BY `id`
+ *   COMMENT 'order records\n[Gravitino] ch.cluster=ck_cluster'
+ *
```
Comment (diqiu50) [inline catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseClusterUtils.java:76]: Do we need an end marker?

File: catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseDatabaseOperations.java (hunk 7 above)
Comment (diqiu50) [reply catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseDatabaseOperations.java]: Querying system table does not handle this case too.  you'd better Add some comments

File: catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseClusterUtils.java (hunk 18 above)
Comment (yuqi1129) [reply catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseClusterUtils.java:76]: Mark "\n[Gravitino] ch.cluster=ck_cluster" will always at the end of the comment, what do you mean here?

Comment (diqiu50) [reply catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseClusterUtils.java:76]: if the user add some comments after `\n[Gravitino] ch.cluster=ck_cluster`, is it a problem?

Comment (yuqi1129) [reply catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseClusterUtils.java:76]: Do you mean users will update the comment without using Gravitino and add something at the end of `\n[Gravitino] ch.cluster=ck_cluster`?

We can't avoid such a problem as long as users can update comments without notifying Gravitino.

Comment (diqiu50) [reply catalogs-contrib/catalog-jdbc-clickhouse/src/main/java/org/apache/gravitino/catalog/clickhouse/operations/ClickHouseClusterUtils.java:76]: So we usually add an end delimiter to avoid things getting mixed together.
