### PR TITLE
[#10725] feat(catalog-glue): Add GlueClientProvider and configuration properties metadata

### LINKED ISSUE #10725: [Subtask] Add GlueClientProvider and configuration properties metadata
### Describe the subtask

Add `GlueClientProvider` (AWS SDK v2 `GlueClient` factory with fail-fast credential validation) and configuration properties metadata classes for the `catalog-glue` module:

- `GlueClientProvider` — builds a `GlueClient` from catalog properties; validates that access key and secret key are either both present or both absent; supports optional endpoint override for LocalStack testing
- `GlueCatalogPropertiesMetadata` — declares all catalog-level properties (`aws-region`, `aws-glue-catalog-id` as required+immutable; credentials as optional+hidden; endpoint, default table format, table type filter as optional)
- `GlueSchemaPropertiesMetadata` / `GlueTablePropertiesMetadata` — stub metadata for schema and table properties
- `GlueCatalogCapability` — declares Glue constraints: no NOT NULL, no DEFAULT values, case-insensitive schema/table names

### Parent issue

https://github.com/apache/gravitino/issues/10708

### PR DESCRIPTION
**Pull request by diqiu50**
### What changes were proposed in this pull request?

Add GlueClientProvider, configuration properties metadata, and capability declarations for the catalog-glue module.

### Why are the changes needed?

AWS connection layer and property definitions are prerequisites for Schema/Table CRUD PRs.

Fix: #10725

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

`./gradlew :catalogs:catalog-glue:test -PskipITs`

### CODE REVIEW

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueClientProvider.java [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+   *     credential keys is provided, or if {@code aws-glue-endpoint} is not a valid URI.
+   */
+  public static GlueClient buildClient(Map<String, String> config) {
+    String region = config.get(GlueConstants.AWS_REGION);
+    Preconditions.checkArgument(
+        !Strings.isNullOrEmpty(region),
+        "Property '%s' is required to create a Glue client",
+        GlueConstants.AWS_REGION);
+
+    GlueClientBuilder builder = GlueClient.builder().region(Region.of(region));
```
[the remark this answers is not in the document]
Comment (diqiu50) [reply catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueClientProvider.java:64]: This is not an issue — passing an empty string will cause an error

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueClientProvider.java [hunk 2]
```diff
@@ -0,0 +1,104 @@
...
+   *
+   * @param config Catalog configuration properties.
+   * @return A configured and ready-to-use {@link GlueClient}.
+   * @throws IllegalArgumentException if {@code aws-region} is missing or blank, if only one of the
+   *     credential keys is provided, or if {@code aws-glue-endpoint} is not a valid URI.
+   */
+  public static GlueClient buildClient(Map<String, String> config) {
+    String region = config.get(GlueConstants.AWS_REGION);
+    Preconditions.checkArgument(
+        !Strings.isNullOrEmpty(region),
```
Comment (yuqi1129) [inline catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueClientProvider.java]: **Bug: blank region not caught.**

`Strings.isNullOrEmpty("   ")` returns `false` — blank strings pass through to `Region.of()`, which may throw an opaque SDK error instead of the helpful message defined here. The Javadoc already says "missing **or blank**", so the guard should match:

```java
!Strings.isNullOrEmpty(region) && !region.isBlank()
```

`testBuildClientBlankRegionThrows` technically passes today because the AWS SDK's `Validate.paramNotBlank` fires, but the error message is not the one we defined.

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueClientProvider.java [hunk 3]
```diff
@@ -0,0 +1,104 @@
...
+        "Property '%s' is required to create a Glue client",
+        GlueConstants.AWS_REGION);
+
+    GlueClientBuilder builder = GlueClient.builder().region(Region.of(region));
+
+    // Static credentials take priority over the default credential chain.
+    // Both keys must be provided together — a partial pair is always a misconfiguration.
+    String accessKey = config.get(GlueConstants.AWS_ACCESS_KEY_ID);
+    String secretKey = config.get(GlueConstants.AWS_SECRET_ACCESS_KEY);
+    boolean hasAccessKey = !Strings.isNullOrEmpty(accessKey);
```
Comment (yuqi1129) [inline catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueClientProvider.java]: **Same blank issue for credentials.**

If a user provides `aws-access-key-id = "   "` (all spaces), `isNullOrEmpty` returns `false`, so `hasAccessKey = true`. If the secret key is absent, the pair-check fires correctly. But if *both* are blank strings, `hasAccessKey == hasSecretKey == true`, and `AwsBasicCredentials.create("   ", "   ")` is called — which silently succeeds at build time and fails with a cryptic auth error at the first API call.

Suggest:
```java
boolean hasAccessKey = !Strings.isNullOrEmpty(accessKey) && !accessKey.isBlank();
boolean hasSecretKey = !Strings.isNullOrEmpty(secretKey) && !secretKey.isBlank();
```

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueCatalogPropertiesMetadata.java [hunk 4]
```diff
@@ -18,20 +18,87 @@
...
+          .put(
+              AWS_REGION,
+              stringRequiredPropertyEntry(
+                  AWS_REGION,
+                  "AWS region for the Glue Data Catalog (e.g. us-east-1)",
+                  true /* immutable */,
+                  false /* hidden */))
+          .put(
+              AWS_GLUE_CATALOG_ID,
+              stringRequiredPropertyEntry(
```
Comment (yuqi1129) [inline catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueCatalogPropertiesMetadata.java]: **Consider making `aws-glue-catalog-id` optional.**

When omitted, Glue defaults to the 12-digit account ID of the caller's credentials. Marking it as `required` forces every user to look up and supply their account ID even when the default is correct. Either:
- Make it optional (with a description note: "When omitted, defaults to the caller's AWS account ID"), or
- Keep it required but explicitly explain in the description why the default is insufficient for Gravitino's use case (e.g. cross-account scenarios).

If there's a specific reason Gravitino always needs the explicit ID, a comment here would prevent future confusion.

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueCatalogPropertiesMetadata.java [hunk 5]
```diff
@@ -18,20 +18,87 @@
...
+                  "Custom Glue endpoint URL for VPC endpoints or LocalStack testing"
+                      + " (e.g. http://localhost:4566)",
+                  false /* immutable */,
+                  null /* defaultValue */,
+                  false /* hidden */))
+          .put(
+              DEFAULT_TABLE_FORMAT,
+              stringOptionalPropertyEntry(
+                  DEFAULT_TABLE_FORMAT,
+                  "Default format for tables created via createTable(). Accepted: iceberg, hive.",
```
Comment (yuqi1129) [inline catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueCatalogPropertiesMetadata.java:90]: **No validation of accepted values for `default-table-format`.**

The description says "Accepted: iceberg, hive" but an invalid value like `"parquet"` will be silently stored and only fail (with a confusing error) at `createTable()` time. Same issue applies to `table-type-filter` on line 96.

Suggest adding validation in the catalog's `initialize()` or in `GlueClientProvider`, or at minimum calling out in the description that unrecognised values are deferred to runtime.

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueConstants.java [hunk 6]
```diff
@@ -0,0 +1,79 @@
...
+  /** Default value for {@link #TABLE_TYPE_FILTER}: expose all table types. */
+  public static final String TABLE_TYPE_FILTER_ALL = "all";
+
+  // -------------------------------------------------------------------------
+  // Glue Table.parameters() keys (passthrough properties)
+  // -------------------------------------------------------------------------
+
+  /**
+   * Glue table format type parameter key stored in {@code Table.parameters()}. Common values:
+   * {@code ICEBERG}, {@code HIVE}, {@code DELTA}, {@code PARQUET}.
```
Comment (yuqi1129) [inline catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueConstants.java]: Minor nit: the values listed here (`ICEBERG`, `HIVE`, `DELTA`, `PARQUET` — uppercase) are Glue `Table.parameters()` values, while `TABLE_TYPE_FILTER`'s accepted values (line 57) are lowercase (`hive`, `iceberg`, ...). They're different namespaces so the casing difference is correct, but a brief note like "Note: these are stored uppercase in Glue parameters; see `TABLE_TYPE_FILTER` for the Gravitino-side filter values" would prevent confusion.

**Review by yuqi1129 — COMMENTED** [review]
Overall the PR is well-structured with good test coverage. A few issues below.

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueClientProvider.java [hunk 7]
```diff
@@ -0,0 +1,104 @@
...
+      builder.credentialsProvider(DefaultCredentialsProvider.create());
+    }
+
+    // Optional custom endpoint override for VPC endpoints or LocalStack testing.
+    String endpoint = config.get(GlueConstants.AWS_GLUE_ENDPOINT);
+    if (StringUtils.isNotBlank(endpoint)) {
+      try {
+        builder.endpointOverride(URI.create(endpoint));
+      } catch (IllegalArgumentException e) {
+        throw new IllegalArgumentException(
```
Comment (yuqi1129) [inline catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueClientProvider.java]: It's not so elegant to catch `IllegalArgumentException`  and then throw an exception with the same type.

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueClientProvider.java [hunk 8]
```diff
@@ -0,0 +1,104 @@
...
+            + "Either provide both keys for static authentication, "
+            + "or omit both to use the default credential chain.",
+        GlueConstants.AWS_ACCESS_KEY_ID,
+        GlueConstants.AWS_SECRET_ACCESS_KEY);
+
+    if (hasAccessKey) {
+      builder.credentialsProvider(
+          StaticCredentialsProvider.create(AwsBasicCredentials.create(accessKey, secretKey)));
+    } else {
+      builder.credentialsProvider(DefaultCredentialsProvider.create());
```
Comment (yuqi1129) [inline catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueClientProvider.java:91]: What's the value of default credential chain?

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueConstants.java [hunk 9]
```diff
@@ -0,0 +1,84 @@
...
+
+  /**
+   * Comma-separated list of table types exposed by {@code listTables()} and {@code loadTable()}
+   * (optional). Accepted values: {@code all}, {@code hive}, {@code iceberg}, {@code delta}, {@code
+   * parquet}. Defaults to {@code all}.
+   */
+  public static final String TABLE_TYPE_FILTER = "table-type-filter";
+
+  /** Default value for {@link #TABLE_TYPE_FILTER}: expose all table types. */
+  public static final String TABLE_TYPE_FILTER_ALL = "all";
```
Comment (yuqi1129) [inline catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueConstants.java]: Rename to `DEFAULT_TABLE_TYPE_FILTER`?

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueTablePropertiesMetadata.java [hunk 10]
```diff
@@ -26,12 +30,36 @@
...
 
-  private static final Map<String, PropertyEntry<?>> PROPERTIES_METADATA = ImmutableMap.of();
+  private static final Map<String, PropertyEntry<?>> PROPERTIES_METADATA =
+      ImmutableMap.<String, PropertyEntry<?>>builder()
+          .put(
+              TABLE_FORMAT_TYPE,
+              stringOptionalPropertyEntry(
+                  TABLE_FORMAT_TYPE,
+                  "Glue table format type stored in Table.parameters(). Common values:"
+                      + " ICEBERG, HIVE, DELTA, PARQUET.",
```
Comment (yuqi1129) [inline catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueTablePropertiesMetadata.java]: Do we only support those four types?

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueClientProvider.java (hunk 8 above)
Comment (diqiu50) [reply catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueClientProvider.java:91]: Add some comments to describe it

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueTablePropertiesMetadata.java (hunk 10 above)
Comment (diqiu50) [reply catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueTablePropertiesMetadata.java]: We only support the `TABLE_FORMAT_TYPE` of ICEBERG, HIVE first

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueConstants.java (hunk 9 above)
Comment (diqiu50) [reply catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueConstants.java]: fixed

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueClientProvider.java [hunk 11]
```diff
@@ -0,0 +1,102 @@
...
+
+    // Static credentials take priority over the default credential chain.
+    // Both keys must be provided together — a partial pair is always a misconfiguration.
+    // Default credential chain order (when both keys are omitted):
+    //   1. Java system properties (aws.accessKeyId / aws.secretAccessKey)
+    //   2. Environment variables (AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY)
+    //   3. Web identity token (EKS / Kubernetes)
+    //   4. ~/.aws/credentials profile file
+    //   5. ECS container task role
+    //   6. EC2 instance profile (IMDSv2)
```
Comment (yuqi1129) [inline catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueClientProvider.java:74]: What if the AKSK is not provided by any of them?

Comment (diqiu50) [reply catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueClientProvider.java:74]: An exception throw on the aws-sdk

**Review by yuqi1129 — APPROVED** [review]

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueClientProvider.java [hunk 12]
```diff
@@ -0,0 +1,102 @@
...
+      builder.credentialsProvider(
+          StaticCredentialsProvider.create(AwsBasicCredentials.create(accessKey, secretKey)));
+    } else {
+      builder.credentialsProvider(DefaultCredentialsProvider.create());
+    }
+
+    // Optional custom endpoint override for VPC endpoints or LocalStack testing.
+    String endpoint = config.get(GlueConstants.AWS_GLUE_ENDPOINT);
+    if (StringUtils.isNotBlank(endpoint)) {
+      builder.endpointOverride(URI.create(endpoint));
```
Comment (yuqi1129) [inline catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueClientProvider.java:97]: `URI.create(endpoint)` will throw `IllegalArgumentException` with a generic message and no property context. Could we catch it and rethrow with explicit config key (for example `aws-glue-endpoint`) and the bad value? That makes misconfiguration diagnosis much easier and matches the fail-fast style used for other properties.
