### PR TITLE
[#9124] Handle negative partNo safely and fix test file typo

### LINKED ISSUE #9124: [Improvement] Fix hasNamePart in FullName.java to check for negative indexes
### What would you like to be improved?

A negative partNo can be passed in; we should check that position >= 0 in the return.

### How should we improve?

Fix and add a unit test.

### PR DESCRIPTION
**Pull request by HarshMehta112**
Fixed #9124

- Negative partNo values can now be safely handled.
- Added unit test cases to verify this behavior.
- Renamed the test file from TestFulllName to TestFullName to fix a minor typo.

### CODE REVIEW

File: clients/cli/src/main/java/org/apache/gravitino/cli/FullName.java [hunk 1]
```diff
@@ -215,7 +215,7 @@ public boolean hasNamePart(int partNo) {
       int length = names.length;
       int position = partNo;
 
-      return position <= length;
+      return position >= 0 && position <= length;
```
Comment (justinmclean) [inline clients/cli/src/main/java/org/apache/gravitino/cli/FullName.java]: While I mentioned a negative value in the issue, we could change this to position> 0, as 0 is not a valid option either.

Comment (HarshMehta112) [reply clients/cli/src/main/java/org/apache/gravitino/cli/FullName.java]: I checked that and pushed the required changes.

**Review by justinmclean — APPROVED** [review]
Thanks for this
