### PR TITLE
[#6786] fix(authz): modify querying roles by user in ROLE_USER_REL relation for JcasbinAuthorizer

### LINKED ISSUE #6786: [Subtask] Introduce JcasbinAuthorizer and GravitinoAdapter for metadata authorization.
### Describe the subtask

Introduce JcasbinAuthorizer and GravitinoAdapter for metadata authorization.

1. JcasbinAuthorizer is a built-in GravitinoAuthorizer implementation in Gravitino, which uses the jcasbin framework to implement metadata authorization.

2.  GravitinoAdapter is a Jcasbin Adapter implementation used to load permission policies from role_meta_securable_object into JcasbinAuthorizer.

### Parent issue

#6762

### PR DESCRIPTION
**Pull request by KyleLin0927**
### What changes were proposed in this pull request?

Currently, the `ROLE_USER_REL` relation in `JDBCBackend` only supports querying users by role, but not querying roles by user. This causes issues in `JcasbinAuthorizer` when trying to load user privileges.

This PR adds support for querying roles by user in the `ROLE_USER_REL` relation by modifying the `listEntitiesByRelation` method in `JDBCBackend`.

### Why are the changes needed?

Fixes #6786

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Ran `./gradlew clean build`

### CODE REVIEW

**Comment by KyleLin0927** [comment]
@hdygxsj plz help to confirm this, thanks.

File: core/src/main/java/org/apache/gravitino/storage/relational/service/RoleMetaService.java [hunk 1]
```diff
@@ -85,6 +85,20 @@ public List<RolePO> listRolesByUserId(Long userId) {
         RoleMetaMapper.class, mapper -> mapper.listRolesByUserId(userId));
   }
 
+  public List<RoleEntity> listRolesByUserIdent(NameIdentifier userIdent) {
+    String metalake = NameIdentifierUtil.getMetalake(userIdent);
+    Long metalakeId = MetalakeMetaService.getInstance().getMetalakeIdByName(metalake);
+    Long userId =
+        UserMetaService.getInstance().getUserIdByMetalakeIdAndName(metalakeId, userIdent.name());
```
Comment (Abyss-lord) [inline core/src/main/java/org/apache/gravitino/storage/relational/service/RoleMetaService.java]: Just use `UserMetaService.getInstance().getUserByIdentifier(nameIdentifier);`.

**Review by Abyss-lord — APPROVED** [review]
LGTM.

**Review by xunliu — APPROVED** [review]
LGTM

**Comment by roryqi** [comment]
Actually, we don't need this. UserPO already has role names.
