### PR TITLE
[#10828] feat(catalog-glue): Implement schema and table CRUD operations

### LINKED ISSUE #10828: [Subtask] catalog-glue: Implement schema and table CRUD operations
## Describe the subtask

Implement schema CRUD (SupportsSchemas), table CRUD (TableCatalog), partition support
(SupportsPartitions), and Glue-to-Gravitino exception mapping for the catalog-glue module.

### What
- `GlueExceptionConverter` — maps AWS Glue exceptions to Gravitino exceptions
- `GlueCatalogOperations` — schema and table CRUD backed by AWS Glue API, with pagination and catalogId support
- `GlueTableOperations` — partition CRUD (SupportsPartitions) for Hive-format tables
- 41 unit tests covering all operations

## Parent issue

https://github.com/apache/gravitino/issues/10708

### PR DESCRIPTION
**Pull request by diqiu50**
### What changes were proposed in this pull request?

Implement schema CRUD, table CRUD, partition support, and exception mapping for the catalog-glue module:

- `GlueExceptionConverter` — maps `EntityNotFoundException`/`AlreadyExistsException`/`InvalidInputException` to Gravitino exceptions
- `GlueCatalogOperations` — implements `SupportsSchemas` and `TableCatalog` backed by AWS Glue API
- `GlueTableOperations` — implements `SupportsPartitions` backed by Glue partition APIs
- `GlueTable` — `newOps()` wired to return `GlueTableOperations`

### Why are the changes needed?

These classes implement the core metadata operations required to make the catalog-glue module functional.

Fix: #10828

### Does this PR introduce _any_ user-facing change?

No. This is internal implementation of the catalog-glue module.

### How was this patch tested?

Unit tests covering schema/table/partition CRUD with mocked `GlueClient`.

### CODE REVIEW

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueTableOperations.java [hunk 1]
```diff
@@ -0,0 +1,265 @@
...
+
+  @Override
+  public String[] listPartitionNames() {
+    List<String> names = new ArrayList<>();
+    String nextToken = null;
+    try {
+      do {
+        GetPartitionsRequest.Builder req =
+            GetPartitionsRequest.builder().databaseName(dbName).tableName(tableName);
+        if (catalogId != null) req.catalogId(catalogId);
```
Comment (yuqi1129) [inline catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueTableOperations.java]: applyCatalogId(req::catalogId)

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueTableOperations.java [hunk 2]
```diff
@@ -0,0 +1,265 @@
...
+    List<String> values = gluePartition.values();
+    String name = buildPartitionName(values);
+
+    String[][] fieldNames = new String[partitionColNames.length][];
+    Literal<?>[] literals = new Literal<?>[partitionColNames.length];
+    for (int i = 0; i < partitionColNames.length; i++) {
+      fieldNames[i] = new String[] {partitionColNames[i]};
+      literals[i] = Literals.stringLiteral(i < values.size() ? values.get(i) : null);
+    }
+    return Partitions.identity(name, fieldNames, literals, Collections.emptyMap());
```
Comment (yuqi1129) [inline catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueTableOperations.java]: Does Glue only support the identity partitioning?

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueCatalogOperations.java [hunk 3]
```diff
@@ -54,11 +145,560 @@ public void testConnection(
...
+      GetTablesRequest.Builder tabReq =
+          GetTablesRequest.builder().databaseName(ident.name()).maxResults(1);
+      applyCatalogId(tabReq::catalogId);
+      try {
+        if (!glueClient.getTables(tabReq.build()).tableList().isEmpty()) {
+          throw new NonEmptySchemaException(
+              "Schema %s is not empty. Use cascade=true to drop it with its tables.", ident.name());
+        }
+      } catch (NonEmptySchemaException e) {
+        throw e;
```
Comment (yuqi1129) [inline catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueCatalogOperations.java]: Remove these two lines.

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueCatalogOperations.java [hunk 4]
```diff
@@ -54,11 +145,560 @@ public void testConnection(
...
+    SerDeInfo serDe =
+        SerDeInfo.builder()
+            .serializationLibrary(properties.get(GlueConstants.SERDE_LIB))
+            .name(properties.get(GlueConstants.SERDE_NAME))
+            .parameters(serdeParams)
+            .build();
+
+    List<String> bucketCols = Collections.emptyList();
+    int numBuckets = 0;
+    if (distribution != null && distribution != Distributions.NONE && distribution.number() > 0) {
```
Comment (yuqi1129) [inline catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueCatalogOperations.java]: When will `distribution.number()` be less than or equal to 0 if it's not `Distributions.NONE`.

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueTable.java [hunk 5]
```diff
@@ -58,12 +62,44 @@
 @ToString
 public class GlueTable extends BaseTable {
 
+  /** Glue client injected after construction to support partition operations. */
+  private GlueClient glueClient;
```
Comment (yuqi1129) [inline catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueTable.java]: Why do we need to add `glueClient` here?

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueTableOperations.java (hunk 2 above)
Comment (diqiu50) [reply catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueTableOperations.java]: Yes, add some comments

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueTable.java (hunk 5 above)
Comment (diqiu50) [reply catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueTable.java]: The GlueTableOperations will use it

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueCatalogOperations.java [hunk 6]
```diff
@@ -54,11 +145,558 @@ public void testConnection(
...
+            ident.name(), comment, columns, props, partitions, distribution, sortOrders);
+
+    CreateTableRequest.Builder req =
+        CreateTableRequest.builder().databaseName(dbName).tableInput(input);
+    applyCatalogId(catalogId, req::catalogId);
+
+    try {
+      glueClient.createTable(req.build());
+    } catch (GlueException e) {
+      throw GlueExceptionConverter.toTableException(e, "table " + ident.name());
```
Comment (yuqi1129) [inline catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueCatalogOperations.java:391]: `createTable` maps every Glue `EntityNotFoundException` through `toTableException`, so creating a table in a missing Glue database will surface as `NoSuchTableException`. The `TableCatalog#createTable` contract declares `NoSuchSchemaException` for this case, and callers/dispatchers rely on that distinction. Please handle `EntityNotFoundException` here as a missing schema (or pass enough context into the converter to choose schema vs table).

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueCatalogOperations.java [hunk 7]
```diff
@@ -54,11 +145,558 @@ public void testConnection(
...
+    // Separate data columns from partition columns
+    int partCount = current.partitioning().length;
+    List<Column> allCols = new ArrayList<>(Arrays.asList(current.columns()));
+    List<Column> dataCols = new ArrayList<>(allCols.subList(0, allCols.size() - partCount));
+    List<Column> partCols =
+        new ArrayList<>(allCols.subList(allCols.size() - partCount, allCols.size()));
+
+    for (TableChange change : changes) {
+      if (change instanceof TableChange.RenameTable) {
+        newName = ((TableChange.RenameTable) change).getNewName();
```
Comment (yuqi1129) [inline catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueCatalogOperations.java]: `RenameTable` can also carry a target schema name. This implementation ignores `getNewSchemaName()`, but Glue `UpdateTable` only updates the table inside the current `databaseName`, so a cross-schema rename would leave the table in the old Glue database while Gravitino metadata may move it to the new namespace. Please reject non-empty/new schema names here, or implement the move explicitly.

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueCatalogOperations.java [hunk 8]
```diff
@@ -54,11 +145,558 @@ public void testConnection(
...
+      Distribution distribution,
+      SortOrder[] sortOrders) {
+
+    int partCount = partitions.length;
+    Preconditions.checkArgument(
+        columns.length >= partCount,
+        "columns.length (%s) must be >= number of partition columns (%s)",
+        columns.length,
+        partCount);
+    int dataCount = columns.length - partCount;
```
Comment (yuqi1129) [inline catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueCatalogOperations.java:550]: This still assumes that the last N entries in `columns` are exactly the partition columns, but only checks the count. If the caller passes `columns=[id, dt]` and `partitions=[identity("region")]`, Glue will create `dt` as the partition key and silently ignore the requested `region` transform. Please validate that each identity transform name matches the corresponding tail column (or derive `partitionKeys` from the transforms instead of slicing `columns`).

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueTableOperations.java [hunk 9]
```diff
@@ -0,0 +1,266 @@
...
+      throw new RuntimeException("Failed to get partition " + partitionName, e);
+    }
+  }
+
+  @Override
+  public Partition addPartition(Partition partition) throws PartitionAlreadyExistsException {
+    Preconditions.checkArgument(
+        partition instanceof IdentityPartition, "Glue only supports identity partitions");
+    IdentityPartition ip = (IdentityPartition) partition;
+    Preconditions.checkArgument(
```
Comment (yuqi1129) [inline catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueTableOperations.java:153]: Please also validate `ip.fieldNames()` against `partitionColNames`, not just the value count. The current code sends values positionally to Glue, so an `IdentityPartition` with field names in the wrong order (or different names with the same count) will create the wrong partition instead of failing fast. Hive does this validation before adding a partition.

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueTableOperations.java [hunk 10]
```diff
@@ -0,0 +1,266 @@
...
+        "Partition values count (%s) must match partition columns count (%s)",
+        ip.values().length,
+        partitionColNames.length);
+
+    List<String> values = new ArrayList<>(ip.values().length);
+    for (Literal<?> v : ip.values()) {
+      values.add(v.value() != null ? v.value().toString() : null);
+    }
+
+    PartitionInput input =
```
Comment (yuqi1129) [inline catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueTableOperations.java:164]: `partition.properties()` are never sent to Glue. `Partition#properties()` is part of the API contract (Hive stores it as partition parameters), but this creates `PartitionInput` without `.parameters(...)`, and `toGravitinoPartition` later returns `Collections.emptyMap()`. That means add/list/get lose all partition properties such as stats or custom metadata. Please persist Glue partition parameters and read them back.

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueCatalogOperations.java (hunk 6 above)
Comment (diqiu50) [reply catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueCatalogOperations.java:391]: fixed

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueCatalogOperations.java (hunk 7 above)
Comment (diqiu50) [reply catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueCatalogOperations.java]: Glue can not support, add some check

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueTableOperations.java (hunk 10 above)
Comment (diqiu50) [reply catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueTableOperations.java:164]: fixed

File: catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueCatalogOperations.java (hunk 8 above)
Comment (diqiu50) [reply catalogs/catalog-glue/src/main/java/org/apache/gravitino/catalog/glue/GlueCatalogOperations.java:550]: This case will cause the Glue API to throw an error.

**Review by yuqi1129 — APPROVED** [review]

**Review by yuqi1129 — APPROVED** [review]
