### PR TITLE
[#10640] fix(iceberg): Remove prefix from config endpoint per Iceberg REST spec

### LINKED ISSUE #10640: [Improvement] Iceberg REST API remove the prefix from the config endpoint URL
### What would you like to be improved?

Image

Image

We ignore the prefix. Actually, prefix represents the catalog name. So we should return catalog properties which prefix represents instead of the default catalog.

### How should we improve?

_No response_

### PR DESCRIPTION
**Pull request by laserninja**
### What changes were proposed in this pull request?

Removed the `prefix` path parameter from the Iceberg REST API config endpoint. The `@Path` annotation was changed from `/v1/{prefix:([^/]*/)?}config` to `/v1/config`, so the endpoint only accepts the `warehouse` query parameter for catalog resolution.

### Why are the changes needed?

Per the [Iceberg REST catalog OpenAPI spec](https://github.com/apache/iceberg/blob/1a2a8a5ecc701629183405ca842f2d1eb23505ee/open-api/rest-catalog-open-api.yaml#L65), the config endpoint does not include a prefix parameter. The Iceberg creator (Ryan Blue) confirmed that "a prefix is not allowed for the config endpoint." The previous implementation incorrectly accepted prefix in the URL path.

Fix: #10640

### Does this PR introduce any user-facing change?

Yes. Requests to `/v1/{prefix}/config` are now rejected (the prefix segment is no longer matched). Clients should use `/v1/config?warehouse=<catalog>` for catalog-specific configuration.

### How was this patch tested?

- Converted parameterized tests to non-prefix versions (`testConfig`, `testConfigWithEmptyWarehouse`, `testConfigWithValidWarehouse`, `testConfigEndpointsContainViewOperations`)
- Added `testConfigRejectsPrefixInUrl` to verify that requests with prefix in the URL are rejected (returns 500 via Jersey's `IcebergExceptionMapper`)
- Removed prefix-specific tests that are no longer applicable (`testIcebergRestValidPrefix`, `testIcebergRestInvalidPrefix`)
- All tests pass: `./gradlew :iceberg:iceberg-rest-server:test --tests TestIcebergConfig`

### CODE REVIEW

File: iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/service/rest/TestIcebergConfig.java [hunk 1]
```diff
@@ -104,12 +117,62 @@ public void testConfigWithNonExistentWarehouses(String warehouse) {
...
+            "true");
+    Assertions.assertEquals(expectedConfig, response.defaults());
+    Assertions.assertEquals(0, response.overrides().size());
+  }
+
+  @Test
+  public void testConfigWithPrefixAndWarehouse() {
+    // When both prefix and warehouse are specified, prefix takes precedence
+    // for catalog resolution, warehouse is used for the prefix default
+    setUrlPathWithPrefix(IcebergRestTestUtil.PREFIX);
```
Comment (bharos) [inline iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/service/rest/TestIcebergConfig.java]: The test sets both prefix and warehouse to IcebergRestTestUtil.PREFIX (same value)
The assertion response.defaults().get("prefix") == PREFIX passes regardless of which branch wins. 
Use distinct values to actually test the priority ?

File: iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergConfigOperations.java [hunk 2]
```diff
@@ -98,13 +99,19 @@ public IcebergConfigOperations(IcebergCatalogWrapperManager catalogWrapperManage
   @Produces(MediaType.APPLICATION_JSON)
   @Timed(name = "config." + MetricNames.HTTP_PROCESS_DURATION, absolute = true)
   @ResponseMetered(name = "config", absolute = true)
-  public Response getConfig(@DefaultValue("") @QueryParam("warehouse") String warehouse) {
-    String catalogName = getCatalogName(warehouse);
+  public Response getConfig(
+      @DefaultValue("") @PathParam("prefix") String prefix,
```
Comment (bharos) [inline iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergConfigOperations.java]: @DefaultValue on a @PathParam is unusual — a path param derived from a regex like ([^/]*/)? already captures an empty string when the segment is absent. It's harmless but maybe we can remove it for clarity. The other endpoints (e.g., IcebergTableOperations) don't annotate their prefix path param with @DefaultValue

**Comment by laserninja** [comment]
1. **Removed `@DefaultValue("")`** from `@PathParam("prefix")` — the regex already handles the absent segment, consistent with other endpoints like `IcebergTableOperations`.

2. **Used distinct values in `testConfigWithPrefixAndWarehouse`** — prefix is set to `IcebergRestTestUtil.PREFIX` (for catalog resolution) while warehouse is set to `"other_warehouse"` (a different string). The assertion now verifies that `response.defaults().get("prefix")` equals the warehouse value, which only passes if the warehouse branch wins for the `"prefix"` default key while the prefix path param wins for catalog resolution.

**Review by bharos — DISMISSED** [review]

File: iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergConfigOperations.java [hunk 3]
```diff
@@ -98,13 +99,19 @@ public IcebergConfigOperations(IcebergCatalogWrapperManager catalogWrapperManage
...
   @Timed(name = "config." + MetricNames.HTTP_PROCESS_DURATION, absolute = true)
   @ResponseMetered(name = "config", absolute = true)
-  public Response getConfig(@DefaultValue("") @QueryParam("warehouse") String warehouse) {
-    String catalogName = getCatalogName(warehouse);
+  public Response getConfig(
+      @PathParam("prefix") String prefix,
+      @DefaultValue("") @QueryParam("warehouse") String warehouse) {
+    String prefixCatalogName = IcebergRESTUtils.getCatalogName(prefix);
+    String catalogName =
+        StringUtils.isNotBlank(prefix) ? prefixCatalogName : getCatalogName(warehouse);
```
Comment (roryqi) [inline iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergConfigOperations.java]: Which catalog should we use if we specified the `prefix` and `warehouse`?

Comment (roryqi) [reply iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergConfigOperations.java]: There is also some discussion about config operations behaviour. You can see https://lists.apache.org/thread/07t5rfcxn3bbbpp75fkr2h1mwdp2o4mn

Comment (laserninja) [reply iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergConfigOperations.java]: Good question. In the current implementation, when both prefix and warehouse are specified, the prefix takes precedence for catalog resolution (since it's the path-level identifier), while the warehouse value is used for the "prefix" key in the response defaults.

However, I see you've raised this same question on the 'Iceberg mailing list'. If the community consensus is different (e.g., warehouse should take precedence, or it should be an error to specify both), I'm happy to update the behavior accordingly. What's your preference here?

Thanks for the pointer, I've read through the thread. The discussion aligns with what this PR does: the prefix represents the catalog name and a 404 is returned when the specified catalog doesn't exist. I'll keep an eye on the spec PR and adjust if the finalized spec diverges from this behavior.

Comment (roryqi) [reply iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergConfigOperations.java]: I prefer that the warehouse takes precedence. I think that prefix provides the default value, warehouse can override it. Wait for the community reply.

Comment (roryqi) [reply iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergConfigOperations.java]: Iceberg creator said that `A prefix is not allowed for the config endpoint, so I don't think you would have this problem.`
So we should remove `prefix` in the url.

Comment (bharos) [reply iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergConfigOperations.java]: Thanks @roryqi for checking this, I too see that the config doesn't have prefix in the spec as well:
https://github.com/apache/iceberg/blob/1a2a8a5ecc701629183405ca842f2d1eb23505ee/open-api/rest-catalog-open-api.yaml#L65

So I guess this change is not required, just need to remove prefix parameter

**Comment by laserninja** [comment]
Updated per feedback — removed prefix from the config endpoint URL entirely, since the Iceberg REST spec does not include prefix for /v1/config. The endpoint now only accepts the warehouse query parameter for catalog resolution. Added a test to verify that requests with prefix in the URL are rejected.

File: iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/service/rest/TestIcebergConfig.java [hunk 4]
```diff
@@ -104,26 +99,16 @@ public void testConfigWithNonExistentWarehouses(String warehouse) {
...
-  @ValueSource(strings = {"PREFIX", "", "\\\n\t\\\'", "\u0024", "\100", "[_~"})
-  void testIcebergRestValidPrefix(String prefix) {
-    String path = injectPrefixToPath(IcebergRestTestUtil.CONFIG_PATH, prefix);
+  @Test
+  public void testConfigRejectsPrefixInUrl() {
+    // Per the Iceberg REST spec, the config endpoint does not accept a prefix.
+    String path = injectPrefixToPath(IcebergRestTestUtil.CONFIG_PATH, IcebergRestTestUtil.PREFIX);
     Response response = getIcebergClientBuilder(path, Optional.empty()).get();
-    Assertions.assertEquals(Status.OK.getStatusCode(), response.getStatus());
+    Assertions.assertNotEquals(Status.OK.getStatusCode(), response.getStatus());
```
Comment (bharos) [inline iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/service/rest/TestIcebergConfig.java]: Is it possible to assert the expected status here ? I guess it might be 404 ? As injecting a prefix makes the URL `/v1/prefix_gravitino/config` which has no matching resource in JAX-RS

**Comment by bharos** [comment]
PR Description is stale now

**Comment by bharos** [comment]
Issue #10640 is titled "Iceberg REST API should return catalog config when prefix is specified." The PR closes it, but the resolution is different. A comment on the issue explaining the conclusion would help track why the issue was resolved this way instead of implementing the originally requested feature.

**Comment by laserninja** [comment]
Addressed all three points:

1. **Status assertion**: Changed `assertNotEquals(200)` to `assertEquals(500)` with a comment explaining that Jersey's `IcebergExceptionMapper` converts the `NotFoundException` into a 500 response for unmatched routes.
2. **PR description**: Updated title and body to reflect the current approach (removing prefix, not adding it).
3. **Issue comment**: Added a comment on #10640 explaining why the resolution differs from the originally requested feature.

**Review by bharos — APPROVED** [review]

**Review by roryqi — APPROVED** [review]
Thanks for your contribution.
