### PR TITLE
[#10841] fix(iceberg): Fix the issues of the table plan endpoint

### LINKED ISSUE #10841: [Bug report] Fix the issues of the planning interface
docker run --rm -d --name grav-plain -p 29001:9001 apache/gravitino:1.2.0
sleep 15

Defect 1: /plan is advertised with a malformed URL template.
Gravitino advertises:   POST /v1/{prefix}/tables/{table}/plan
Iceberg REST OpenAPI spec (apache/iceberg main, operationId planTableScan) defines:
                         POST /v1/{prefix}/namespaces/{namespace}/tables/{table}/plan
The /namespaces/{namespace} segment is missing from Gravitino's advertisement.
curl -s http://localhost:29001/iceberg/v1/config | python3 -m json.tool | grep plan

Create namespace and table so the next probe isn't a table-lookup failure
curl -sS -X POST -H "Content-Type: application/json" \
  -d '{"namespace": ["t"]}' \
  http://localhost:29001/iceberg/v1/namespaces

curl -sS -X POST -H "Content-Type: application/json" \
  -d '{"name": "tbl", "schema": {"type": "struct", "schema-id": 0, "fields": [{"id": 1, "name": "id", "type": "long", "required": false}]}}' \
  http://localhost:29001/iceberg/v1/namespaces/t/tables

Defect 2: /plan is not wired as a Jersey route at either path.
Both probes below return 500-wrapped javax.ws.rs.NotFoundException
from org.glassfish.jersey.server.ServerRuntime — no route registered,
not an Iceberg-handler table-lookup miss.
curl -i -sS -X POST -H "Content-Type: application/json" -d '{"select": ["*"]}' \
  http://localhost:29001/iceberg/v1/tables/tbl/plan

curl -i -sS -X POST -H "Content-Type: application/json" -d '{"select": ["*"]}' \
  http://localhost:29001/iceberg/v1/namespaces/t/tables/tbl/plan

### PR DESCRIPTION
**Pull request by roryqi**
### What changes were proposed in this pull request?

Fix the issues of the table plan endpoint

### Why are the changes needed?

Fix: #10841

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Add UT.

### CODE REVIEW

File: iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergTableOperations.java [hunk 1]
```diff
@@ -493,7 +493,7 @@ public Response getTableCredentials(
    * @return Response containing the scan plan with tasks
    */
   @POST
-  @Path("{table}/scan")
+  @Path("{table}/plan")
```
Comment (yuqi1129) [inline iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergTableOperations.java:496]: Could you leave some comments on why we renamed it from `scan` to `plan`?

Comment (roryqi) [reply iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergTableOperations.java:496]: scan is wrong path. We shouldn't use `scan`.

**Comment by yuqi1129** [comment]
@diqiu50 
I have no more comments, would you like to take a look?

File: iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergConfigOperations.java [hunk 2]
```diff
@@ -57,6 +57,12 @@ public class IcebergConfigOperations {
 
   private final IcebergCatalogWrapperManager catalogWrapperManager;
 
+  // Iceberg 1.10.1's Endpoint.V1_SUBMIT_TABLE_SCAN_PLAN uses a broken path that is missing the
+  // namespaces/{namespace} segment (fixed in apache/iceberg#14120, targeting 1.11.x). We override
```
Comment (bharos) [inline iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergConfigOperations.java]: nit : Add as a TODO for future reference

**Review by bharos — DISMISSED** [review]

File: iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergConfigOperations.java (hunk 2 above)
Comment (roryqi) [reply iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergConfigOperations.java]: OK.

Comment (roryqi) [reply iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergConfigOperations.java]: Fixed.

**Review by bharos — APPROVED** [review]
LGTM
