### PR TITLE
fix: disable MUI DataGrid row hover highlighting

### LINKED ISSUE #3290: [Improvement] Rows in Gravitino UI are highlighed on rollover but no action can be done
### What would you like to be improved?

In the metalake page, the catalog page and the tables pages rows highlight as you roll over them, but no user action can be performed. For instance, a user may expect the catalog details to show up when clicking on a catalog row.

### How should we improve?

Provide a user action or disable highlighting.

### PR DESCRIPTION
**Pull request by kerenpas**
✅ Explains what changes were made - CSS overrides in the theme file
✅ Explains why changes are needed - Addresses the unwanted hover behavior
✅ Describes user-facing changes - Visual improvement
✅ Mentions testing - How you verified the fix works
✅ References the issue - Fixes #3290 will automatically link and close the issue when merged

### CODE REVIEW

File: web/web/src/lib/theme/mui.js [hunk 1]
```diff
@@ -340,13 +340,14 @@ const createMuiTheme = (config = {}) => {
                 paddingLeft: theme.spacing(5),
                 paddingRight: theme.spacing(5),
                 '&.MuiButton-containedPrimary:hover': {
-                  boxShadow: `0 2px 4px 0 ${alpha(primary.main, 0.4)}`
+                  boxShadow: `0 2px 4px 0 ${alpha(primary.main, 0.4)}`,
+                  backgroundColor:'yellow'
```
Comment (justinmclean) [inline web/web/src/lib/theme/mui.js]: Did you mean to change to yellow?

File: web/web/src/lib/theme/mui.js [hunk 2]
```diff
@@ -340,13 +340,14 @@ const createMuiTheme = (config = {}) => {
...
                 },
                 '&.MuiButton-containedSecondary:hover': {
                   boxShadow: `0 2px 4px 0 ${alpha(secondary.main, 0.4)}`
                 },
                 '&.MuiButton-containedSuccess:hover': {
-                  boxShadow: `0 2px 4px 0 ${alpha(success.main, 0.4)}`
+                  boxShadow: `0 2px 4px 0 ${alpha(success.main, 0.4)}`
```
Comment (justinmclean) [inline web/web/src/lib/theme/mui.js]: no need for space at the end of the line

File: web/web/src/lib/theme/mui.js (hunk 1 above)
Comment (kerenpas) [reply web/web/src/lib/theme/mui.js]: ops my bad, sure this will be remove

File: web/web/src/lib/theme/mui.js (hunk 2 above)
Comment (kerenpas) [reply web/web/src/lib/theme/mui.js]: sure

**Comment by jerryshao** [comment]
@LauraXia123 can you please help to review?

**Comment by LauraXia123** [comment]
please fix the ci issue by `pnpm format`

**Comment by kerenpas** [comment]
@LauraXia123  thank you for the review.
could you please approve to run the 10 workflows  to be run.

**Review by LauraXia123 — APPROVED** [review]
LGTM, thank you for your contribution.

**Comment by kerenpas** [comment]
@LauraXia123, this was my first PR to get into this project and understand how to work with it. Could you pls recommend me for another more complex issue? thanks for review

**Comment by LauraXia123** [comment]
@kerenpas  You can follow the issue list, first.
